Implement In memory kv store in go
null-channel/null-db pull request #1
Opened 2022-01-19 00:57 UTC by s1ntaxe770r

2022-01-19 04:15 UTC, Klaven reviewed
two small comments.
1) (see in code)
2) No way to delete a value? only insert and read? - this becomes harder with things like replication and sharding so I think its important, even at this state when it's "easy"
3) I lied. three things. This looks good for the most part. Keep up the solid work. I love the readme, lets keep adding to the readme so if someone stubles across this repo it's golden without watching any of my vidoes :)

2022-01-19 04:15 UTC, Klaven commented on go/all-in-memory/pkg/kv/kv.go
> +	kv.mu.Lock()
should this not be `kv.mu.RLock()` As it stands you are locking it for all threads. This is not needed as you can have multiple readers at the same time on a map. Just not multiple writers.

2022-01-19 06:39 UTC, s1ntaxe770r commented on go/all-in-memory/pkg/kv/kv.go
> +	kv.mu.Lock()
Oh thanks, I was really confused as to which one to use

2022-01-19 15:49 UTC, Klaven requested changes
I think I must have poorly explained myself. `RLock` is for reading, non-mutating code. aka `get` while the `Lock` is for mutating code and is mutually exclusive.

this looks to explain it well.
https://stackoverflow.com/questions/19148809/how-to-use-rwmutex

2022-01-19 15:49 UTC, Klaven commented on go/all-in-memory/pkg/kv/kv.go
> +	defer kv.mu.RUnlock()
you are mutating here. this should be a "Lock", not rlock and runlock.

2022-01-19 15:49 UTC, Klaven commented on go/all-in-memory/pkg/kv/kv.go
> +	defer kv.mu.RUnlock()
this is mutating. so it needs to be lock and unlock. not a reader lock.

2022-01-19 16:07 UTC, s1ntaxe770r commented on go/all-in-memory/pkg/kv/kv.go
> +	defer kv.mu.RUnlock()
Thank you for clarifying

2022-01-19 21:25 UTC, Klaven approved these changes
/lgtm

2022-01-19 21:49 UTC, s1ntaxe770r commented
Shall I merge?

2022-01-27 05:08 UTC, Klaven commented
can you rebase this and fit it into the "new" folder structure. I apologize. Originally I had your code in the re-organization but something happened as you know. I super apologize for the trouble.

2022-01-29 00:38 UTC, merged